# Generated by Django 3.2.2 on 2021-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, null=True)),
                ('author_1', models.CharField(max_length=120)),
                ('author_2', models.CharField(max_length=120)),
                ('author_3', models.CharField(max_length=120)),
                ('sentiment_1', models.CharField(max_length=120)),
                ('sentiment_2', models.CharField(max_length=120)),
                ('sentiment_3', models.CharField(max_length=120)),
            ],
        ),
    ]
