# Generated by Django 3.2.3 on 2021-06-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_label', '0003_auto_20210603_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
