# Generated by Django 3.2.3 on 2021-06-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_label', '0004_auto_20210604_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='post_id',
            new_name='post_ID',
        ),
    ]
