# Generated by Django 3.2.3 on 2021-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_label', '0005_rename_post_id_label_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='post_ID',
            field=models.IntegerField(max_length=6),
        ),
    ]
