# Generated by Django 3.2.3 on 2021-06-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_label', '0007_alter_label_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_labels',
            field=models.IntegerField(default=0),
        ),
    ]
