# Generated by Django 3.2.3 on 2021-06-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_label', '0009_label_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='content',
        ),
    ]
